# Використовуються базові конфігурації:
defaults:
  # Основні налаштування Modulus
  - modulus_default
  # Вибір архітектури нейронної мережі: використовуємо повністю з'єднану (fully connected)
  - arch:
      - fully_connected
  # Планувальник (scheduler) для коригування learning rate: tf_exponential_lr (експоненціальне зниження)
  - scheduler: tf_exponential_lr
  # Оптимізатор: Adam (рекомендований для стабільного і ефективного навчання)
  - optimizer: adam
  # Функціонал loss: сумування всіх втрат (sum)
  - loss: sum
  # _self_ означає, що налаштування поточної конфігурації включаються в підсумкову конфігурацію
  - _self_

# Налаштування параметрів тренування
training:
  # Максимальна кількість кроків, які буде виконувати тренувальний цикл
  max_steps: 1000000
  # Частота запису результатів (збереження знімків/виводів) – кожні 5000 кроків
  rec_results_freq: 3000
  # Частота запису обмежень (constraints), які використовуються для обчислення функції втрат – кожні 10000 кроків
  rec_constraint_freq: 5000

  rec_validation_freq: 5000

arch:
  fully_connected:
    layer_size: 600
    nr_layers: 6
# Розміри батчів для різних типів обмежень (boundary/inlet/outlet тощо)
batch_size:
  # Кількість точок для граничного обмеження на вході
  inlet: 250
  # Кількість точок для граничного обмеження на виході
  outlet: 250
  # Для стін (наприклад, no-slip умова, де швидкість = 0)
  walls: 700
  # Для поверхні дрона (ділянки, де застосовується певна умова, напр. no-slip)
  drone: 1200
  # Для кожної з лопатей (blade1, blade2, blade3, blade4) – кількість точок, що використовуються для обмеження
  blade1: 400
  blade2: 400
  blade3: 400
  blade4: 400
  # Для внутрішніх точок домену (interior constraints, де застосовуються рівняння плину, наприклад, рівняння Нав'є-Стокса)
  interior: 4300

# Налаштування планувальника (scheduler) для коригування learning rate
scheduler:
  # Коефіцієнт зниження learning rate після певних кроків
  decay_rate: 0.95
  # Кількість кроків, після яких learning rate буде знижуватися експоненціальним методом (зменшення кожні 15000 кроків)
  decay_steps: 15000
