


defaults :
  - modulus_default
  - arch:
      - fourier
  - scheduler: tf_exponential_lr
  - optimizer: adam
  - loss: sum
  - _self_

jit: false

optimizer:
  lr: 5e-5
# Налаштування параметрів тренування
training:
  # Максимальна кількість кроків, які буде виконувати тренувальний цикл
  max_steps: 200000
  # Частота запису результатів (збереження знімків/виводів) – кожні 5000 кроків
  rec_results_freq: 2000
  # Частота запису обмежень (constraints), які використовуються для обчислення функції втрат – кожні 10000 кроків
  rec_constraint_freq: 2000

  rec_validation_freq: 2000


# Розміри батчів для різних типів обмежень (boundary/inlet/outlet тощо)
batch_size:
  # Кількість точок для граничного обмеження на вході
  inlet: 256
  # Кількість точок для граничного обмеження на виході
  outlet: 256
  # Для внутрішніх точок домену (interior constraints, де застосовуються рівняння плину, наприклад, рівняння Нав'є-Стокса)
  interior: 2048
  interior_init: 2048
  wf_pt : 512

# Налаштування планувальника (scheduler) для коригування learning rate
scheduler:
  # Коефіцієнт зниження learning rate після певних кроків
  decay_rate: 0.95
  # Кількість кроків, після яких learning rate буде знижуватися експоненціальним методом (зменшення кожні 15000 кроків)
  decay_steps: 5000
