


defaults :
  - modulus_default
  - arch:
#      - siren
#      - fully_connected
      - modified_fourier
  - scheduler: tf_exponential_lr
  - optimizer: adam
  - loss: sum
  - _self_

jit: false

optimizer:
  lr: 1e-3

# Налаштування параметрів тренування
training:
  # Максимальна кількість кроків, які буде виконувати тренувальний цикл
  max_steps: 1000000
  # Частота запису результатів (збереження знімків/виводів) – кожні 5000 кроків
  rec_results_freq: 2000
  # Частота запису обмежень (constraints), які використовуються для обчислення функції втрат – кожні 10000 кроків
  rec_constraint_freq: 2000

  rec_validation_freq: 2000

arch:
  # 1) Fully connected MLP
  fully_connected:
    layer_size: 512
    nr_layers: 6

  # 2) Modified Fourier‐feature MLP
  modified_fourier:
    layer_size: 512
    nr_layers: 6
    frequencies:
      axis:     [0.0, 0.5, 1.0, 1.5, 2.0, 2.5]
      diagonal: [0.0, 0.5, 1.0, 1.5, 2.0, 2.5]

  # 3) SIREN: sinusoidal activation network
  SirenConf:
    layer_size: 512
    layers:     8

# Розміри батчів для різних типів обмежень (boundary/inlet/outlet тощо)
batch_size:
  # Кількість точок для граничного обмеження на вході
  inlet: 64
  # Кількість точок для граничного обмеження на виході
  outlet: 64
  # Для внутрішніх точок домену (interior constraints, де застосовуються рівняння плину, наприклад, рівняння Нав'є-Стокса)
  interior: 2048

  walls : 1024

  drone: 1024

# Налаштування планувальника (scheduler) для коригування learning rate
scheduler:
  # Коефіцієнт зниження learning rate після певних кроків
  decay_rate: 0.95
  # Кількість кроків, після яких learning rate буде знижуватися експоненціальним методом (зменшення кожні 15000 кроків)
  decay_steps: 4000


stop_criterion:
  # Ми будемо стежити за загальною втратою ("loss") і хочемо її мінімізувати:
  metric: loss
  # Різниця в 0.01 — вважаємо непомітною зміну меншу за цю величину:
  min_delta: 0.01
  # Якщо протягом 10 000 кроків (6 перевірок по 2 000 кроків) loss не зменшився
  # мінімум на 1e-2, — зупиняємо навчання
  patience: 12000
  #  кожні 1000 кроків перевіряємо, чи metric покращився
  freq: 2000
  # Мінімізуємо: зупиняємось коли втрата НЕ зменшується
  mode: min
  # Жорсткий чи не жорсткий ріжок
  strict: false
